name: Call a reusable workflow

on:
  push:
  pull_request:

jobs:
  call-workflow:
    uses: dfcastro1/workflow-a/.github/workflows/work.yml@v1

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
