name: Call a reusable workflow

on:
  pull_request:
    branches:
      - master

jobs:
  call-workflow:
    uses: dfcastro1/workflow-a/.github/workflows/work.yml

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: dfcastro1/workflow-a/.github/workflows/work.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}