name: Call a reusable workflow

on:
  push:
    branches:
    - master

jobs:
  call-workflow:
    uses: dfcastro1/workflow-a/.github/workflows/work.yml

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: dfcastro1/workflow-a/.github/workflows/work.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  teste:
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16